# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'iosApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iosApp
  pod 'composeApp', :path => '../androidApp'
end

post_install do |installer|
  ignored_targets = ['KotlinGradlePlugin', 'composeApp']

  installer.pods_project.targets.each do |target|
    next if ignored_targets.include?(target.name)

    puts "✅ Patching deployment target for: #{target.name}"

    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end
